# Generated by Django 5.2.5 on 2025-09-04 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('default_shipping_address_line_1', models.CharField(blank=True, max_length=255)),
                ('default_shipping_address_line_2', models.CharField(blank=True, max_length=255)),
                ('default_shipping_city', models.CharField(blank=True, max_length=100)),
                ('default_shipping_state', models.CharField(blank=True, max_length=100)),
                ('default_shipping_postal_code', models.CharField(blank=True, max_length=20)),
                ('default_shipping_country', models.CharField(blank=True, max_length=100)),
                ('default_billing_address_line_1', models.CharField(blank=True, max_length=255)),
                ('default_billing_address_line_2', models.CharField(blank=True, max_length=255)),
                ('default_billing_city', models.CharField(blank=True, max_length=100)),
                ('default_billing_state', models.CharField(blank=True, max_length=100)),
                ('default_billing_postal_code', models.CharField(blank=True, max_length=20)),
                ('default_billing_country', models.CharField(blank=True, max_length=100)),
                ('newsletter_subscription', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
